name: Build, Push, and Deploy (Blue/Green)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-api-server:latest

      - name: Deploy to server via SSH (Blue/Green)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            #!/bin/bash
            set -e

            # 현재 활성 컨테이너 확인 (blue or green)
            ACTIVE=$(docker ps --filter "name=my-api-blue" --format "{{.Names}}")
            if [ "$ACTIVE" == "my-api-blue" ]; then
              NEW_CONTAINER="my-api-green"
              NEW_PORT=4001
            else
              NEW_CONTAINER="my-api-blue"
              NEW_PORT=4000
            fi

            # 새 컨테이너 실행
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-api-server:latest
            docker stop $NEW_CONTAINER || true
            docker rm $NEW_CONTAINER || true
            docker run -d --name $NEW_CONTAINER -p $NEW_PORT:4000 --env-file /root/.env ${{ secrets.DOCKERHUB_USERNAME }}/my-api-server:latest

            # Nginx 설정 파일 스위칭 (예시: 심볼릭 링크 교체)
            ln -sf /etc/nginx/sites-available/api-$NEW_CONTAINER /etc/nginx/sites-enabled/api
            nginx -s reload 